name: ALLAURMONO
description: ひびのできごとなどをたまにかきます
author: "Atsushi Nagaki"
highlighter: pygments
permalink: none
markdown: redcarpet
markdown_ext: markdown,md
exclude:
  - README.md
  - s3_website.yml
  - Gemfile
  - Gemfile.lock
url: http://blog.nagaki.me
sass:
  sass_dir: _sass
  style: :compressed
gems:
  - jekyll-sitemap
