name: ALLAURMONO
description: ひびのできごとなどをたまにかきます
author: "Atsushi Nagaki"
highlighter: rouge
permalink: none
markdown_ext: markdown,md
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor
url: https://blog.nagaki.me
sass:
  sass_dir: _sass
  style: :compressed