name: ALLAURMONO
description: ひびのできごとなどをたまにかきます
author: "Atsushi Nagaki"
pygments: true
permalink: none
markdown: rdiscount
markdown_ext: markdown,md
exclude:
  - README.md
  - s3_website.yml
  - Gemfile
  - Gemfile.lock
url: http://blog.nagaki.me
